

services:
  db:
    image: postgres:16
    restart: always
    container_name: pd-test-db
    environment:
      POSTGRES_USER: keshia-pd
      POSTGRES_PASSWORD: keshia123
      POSTGRES_DB: pd-test-db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pd-test-app
    ports:
      - "3000:3000"
    environment:
      # 🔗 Setting DB
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: keshia-pd
      DB_PASSWORD: keshia123
      DB_NAME: pd-test-db
      
      # 🔒 Aditional
      JWT_SECRET: YOUR_VERY_SECURE_SECRET_KEY
      PORT: 3000
    depends_on:
      - db
    command: npm run dev
    volumes:
      - ./app:/usr/src/app
